# Generated by Django 2.2.4 on 2023-04-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('region_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
                ('country_code_iso3', models.CharField(max_length=10)),
                ('country_capital', models.CharField(max_length=255)),
                ('country_tld', models.CharField(max_length=10)),
                ('continent_code', models.CharField(max_length=10)),
                ('in_eu', models.BooleanField()),
                ('postal', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(max_length=255)),
                ('utc_offset', models.CharField(max_length=10)),
                ('country_calling_code', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('currency_name', models.CharField(max_length=255)),
                ('languages', models.CharField(max_length=255)),
                ('country_area', models.FloatField()),
                ('country_population', models.BigIntegerField()),
                ('asn', models.CharField(max_length=255)),
                ('org', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
