# Generated by Django 2.2.4 on 2023-04-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnection',
            name='version',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
