# Generated by Django 2.2.4 on 2023-04-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truths', '0002_auto_20230412_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnection',
            name='asn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='continent_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='country',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='country_area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='country_calling_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='country_capital',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='country_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='country_code_iso3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='country_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='country_population',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='country_tld',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='currency_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='in_eu',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='languages',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='network',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='org',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='postal',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='region_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='timezone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='utc_offset',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
